apiVersion: v1
kind: ConfigMap
metadata:
  name: factory-config
  namespace: factory
data:
  TOPIC: dados-sensores
  MAX_TEMPERATURE: "40.0"
  MIN_TEMPERATURE: "10.0"
  MAX_VIBRATION: "1.0"
  MIN_VIBRATION: "0.1"
  MYSQL_HOST: db
  MYSQL_USER: user
  MYSQL_DATABASE: url_shortener