apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: factory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: rodperoba/factory-consumer:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: factory-config
            - secretRef:
                name: factory-secret
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: factory
spec:
  type: NodePort
  selector:
    app: consumer
  ports:
    - port: 5001
      targetPort: 5001
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-hpa
  namespace: factory
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50